### ISSUE TITLE
Mutable methods in wit resources

### ISSUE THREAD

**Issue by tqwewe** [bytecodealliance/wit-bindgen#178] opened 2022-03-21 13:39 UTC
I'm looking into using resources with the following .wit file:
```
resource aggregate {
  static new: function(id: string) -> aggregate
  apply-events: function(event: list<list<u8>>)
}
```
Which generates:
```rust
pub trait Aggregate {
    fn new(id: String,) -> wit_bindgen_rust::Handle<super::Aggregate>;
    fn apply_events(&self,event: Vec<Vec<u8>>,);
}
```
But using the [online demo](https://bytecodealliance.github.io/wit-bindgen/) to see the generated rust code for export, the `apply-events` method takes `&self`. But what if I want to mutate self with `&mut self`, is this possible?

**Comment by alexcrichton** [comment] 2022-03-21 14:42
This is currently due to the assumption that components allow for being recursively entered. This means that if Rust handed out `&mut T` then it would be memory unsafe to recursively call the component. This means that there's no way to use `&mut self` and you need to use interior mutability such as `Cell<T>` or `RefCell<T>`.

I believe the most recent iteration of the component model disallows recursively entering a component, though, so a future iteration of wit-bindgen for the updated component model will likely define all methods with `&mut self` since you'll have exclusive access at all times.

**Comment by alexcrichton** [comment] 2022-03-21 17:30
Ok I'll leave this open so when we see this again I can confirm that this change was made or not.

**Comment by alexcrichton** [comment] 2022-04-20 16:16
Ok I'm going to close this in favor of https://github.com/bytecodealliance/wit-bindgen/issues/201 since this is part of the new canonical ABI updates.

**Closed by alexcrichton** 2022-04-20 16:16 UTC
