### ISSUE TITLE
Large `record` has escaped the trait boundary for trait WasmTy

### ISSUE THREAD

**Issue by Mossaka** [bytecodealliance/wit-bindgen#171] opened 2022-03-10 04:32 UTC
I have the following wit file
```
record long {
    a: string,
    b: string,
    c: string,
    d: string,
    e: string,
    f: string,
    g: string,
    h: string,
    i: string,
}

f: function(a: long) -> string
```

and then I tried to generate the import binding for wasmtime: 
`wit_bindgen_wasmtime::import!("./long-record.wit");`

The compile error says
```
error[E0277]: the trait bound `(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32): WasmTy` is not satisfied
   --> src/main.rs:6:1
    |
6   | wit_bindgen_wasmtime::import!("./long-record.wit");
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `WasmTy` is not implemented for `(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32)`
    |
    = note: required because of the requirements on the impl of `WasmParams` for `(i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32)
```

Are there alternative ways to resolve this? Thanks!

**Comment by peterhuene** [comment] 2022-03-10 05:39
I think this is a dupe of #134.

The problem is that the canonical ABI representation of this many fields (each one requires two `i32`s) exceeds the number of parameters that `Func::wrap` supports in the Wasmtime API, so the generated code won't compile.

**Closed** 2022-03-10 16:57 UTC

**Comment by Mossaka** [comment] 2022-03-10 16:58
Could you please hint a workaround? @peterhuene @alexcrichton Thanks!
