### ISSUE TITLE
Sharing resource definition between a JS host and Rust guest

### ISSUE THREAD

**Issue by fabricedesre** [bytecodealliance/wit-bindgen#305] opened 2022-08-30 16:50 UTC
I'm trying to build a system where the JS host can implement delegates and pass them to the Rust side - think about abstracting cryptographic operations to use the WebCrypto API in a browser for instance.

Unfortunately it looks like the 2 JS files generated don't play well together in that case. I put up a runnable demo at https://github.com/fabricedesre/wit-test

Is that a codegen limitation, or something more fundamental?

**Comment by Kylebrown9** [comment] 2022-08-30 17:25
I'm not sure exactly what you're trying to do, but I can hopefully point you in the right direction.

Here are some relevant resources related to what you're trying to do
* [WASI Crypto](https://github.com/WebAssembly/wasi-crypto) - A standardized API for cryptographic primitives
* Related questions #292, #293, which we expect are solved by the next bullet
* Profiles (`*.world`) - A new file that allows you to define the various imports and exports of a module/component together in one place (see [component-model draft PR](https://github.com/WebAssembly/component-model/pull/83) and open issue [here](https://github.com/bytecodealliance/wit-bindgen/issues/265))

**Comment by fabricedesre** [comment] 2022-08-30 17:44
Thanks, I'll take a look - indeed #293 and profiles seems to cover the same problem space.

If that matters, my target environment is browsers, so WASI & wasmtime are less directly relevant to me.

**Comment by alexcrichton** [comment] 2022-09-06 18:22
I think that this is a duplicate of https://github.com/bytecodealliance/wit-bindgen/issues/266 (importing/exporting things at the same time) so I'm going to close this in favor of that.

**Closed by alexcrichton** 2022-09-06 18:22 UTC
