### ISSUE TITLE
wit-bindgen go: support resources

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/wit-bindgen#696] opened 2023-10-11 16:14 UTC

**Comment by Mossaka** [comment] 2023-10-20 21:40
Duplicate of #615

**Comment by Mossaka** [comment] 2023-10-29 05:23
I've started working on adding runtime tests for rust and C to the repo. Once this is done I will start implementing resources in Go and write more tests!

**Closed** 2023-11-27 22:46 UTC
Labels: gen-tinygo
